# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-05 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': '购物车'},
        ),
        migrations.AddField(
            model_name='cart',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='updatetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterIndexTogether(
            name='cart',
            index_together=set([('user', 'item')]),
        ),
    ]
