# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-07 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0006_auto_20181105_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='goods',
        ),
        migrations.AlterIndexTogether(
            name='cart',
            index_together=set([('user', 'goods')]),
        ),
    ]
